version: '2'
plugins:
  eslint:
    enabled: true
    channel: eslint-5
    config:
      config: ./.eslintrc.json
  fixme:
    enabled: true
	git-legal:
    enabled: true
  markdownlint:
    enabled: true
  stylelint:
    enabled: true
